config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/interviews/new/:user_id/:job_id', to: 'interviews#new', as: 'new_interview'
  resources :interviews, only: [:show, :new, :create]
  

  resources :interviews do
    collection do
      get :new
    end
  end
  resources :interviews do
    member do
      get :edit
      patch :update
    end
  end
  
  resources :applied_jobs do
    collection do
      get :display
      get :myjob
      get :subscribe
    end
  end
  resources :jobs do 
    collection do 
      get :all_user
      get :applicant
    end
  end
  # root to:'registration#sign_up'
  devise_scope :user do
   root to: "devise/registrations#new"
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/applied_job.rb
class AppliedJob < ApplicationRecord
	belongs_to :user
	belongs_to :job
	#validates :contactno,:name,:surname,:user_id,:email,:experience, presence: true
	 has_one_attached :resume
end

app/models/interview.rb
class Interview < ApplicationRecord
	belongs_to :user
	belongs_to :job
	validates :date,:address,presence: { message: "can't be blank" }
end

app/models/job.rb
class Job < ApplicationRecord
	validates :title,:jobtype,:salary,:location, :description,presence: { message: "can't be blank" }
	belongs_to :user	
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   validates :name,:role, presence: { message: "can't be blank" }
    has_many :applied_jobs  
    has_many :jobs   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

    before_action :update_allowed_parameters, if: :devise_controller?
     before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password, :role)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :surname, :email, :password, :current_password,:role)}
  end

  def after_sign_in_path_for(resource)
    if resource.role == "admin" or resource.role == "company"
      jobs_path
    elsif resource.role == "user"
      applied_jobs_path
    else
      root_path
    end
  end


  def after_sign_out_path_for(resource_or_scope)
  new_user_session_path
  end
   
   def after_sign_up_path_for(resource) 
    
    new_user_session_path
   end 
   
    def create
    super
    flash[:alert] = @user.errors.full_messages unless @user.errors.empty?
    end
end

app/controllers/applied_jobs_controller.rb
class AppliedJobsController < ApplicationController
   
  def index
    #@jobs = Job.all
    @q = Job.ransack(params[:q])
    @jobs = @q.result(distinct:true)
  end

  def show
    @job = Job.find(params[:id])    
  end

  def new
     @job = Job.find(params[:job_id])
     @applied_job = AppliedJob.new
  end

  def create
    @applied_job = AppliedJob.new(applied_job_params)
    @applied_job.user = current_user
    @applied_job.resume.attach(params[:applied_job][:resume])   
      if AppliedJob.exists?(user_id: params[:applied_job][:user_id], job_id: params[:applied_job][:job_id])
         flash[:error] = "you have  already applied for this  Job"
         render :new
      elsif @applied_job.save
       CrudAppliedjobMailer.create_notification(@applied_job,current_user).deliver_later
       redirect_to display_applied_jobs_path
      else
       render :new  
      end
   end

  def display
  end

  def myjob
    @job_ids = AppliedJob.where(user_id:current_user.id).pluck(:job_id)
    @jobs=Job.where(id: @job_ids)
  end


   private
   def applied_job_params
      params.require(:applied_job).permit(:job_id,:user_id,:name,:surname,:email,:contactno,:experience ,:resume)
   end
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
	  def show
      @interview = Interview.find(params[:id])
     # @interview = Interview.find_by(user_id: params[:user_id], job_id: params[:job_id])
    end

    def edit
      @interview = Interview.find(params[:id])  
    end

    def update
      @interview = Interview.find(params[:id])
      if @interview.update(interview_params)
        redirect_to @interview, notice: "Interview status updated successfully."
      else
        render :edit
      end
    end

    def new 
      @interview = Interview.new
      @user_id = params[:user_id]
      @job_id = params[:job_id]
    end
    
    def create
      @interview = Interview.new(interview_params)

      if Interview.exists?(user_id: params[:interview][:user_id], job_id: params[:interview][:job_id])
        flash[:error] = "Interview already exists for this User and Job"
        render :new

      elsif @interview.save
        CrudAppliedjobMailer.interview_notification(@interview).deliver_later
        redirect_to interview_path(@interview)
      else
        render :new
      end
    end
    
      private
       def interview_params
        params.require(:interview).permit(:address,:date,:user_id,:job_id,:status)
      end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

 before_action :authorize_admin_or_company

	def index
    if current_user.role == 'admin'
       @jobs = Job.all
    else 
     @jobs = Job.where(user_id: current_user.id)
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    # binding.pry
    @job = Job.new(job_params.merge(user_id: current_user.id))
 
  if @job.save
    redirect_to @job
  else
    
    render 'new'                             
  end
 end
  def update
  @job = Job.find(params[:id])
 
  if @job.update(job_params)
    redirect_to @job
  else
    render 'edit'
  end
 end
 def destroy
  @job = Job.find(params[:id])
  @job.destroy
 
  redirect_to jobs_path
  end
  def all_user
     @all_user = User.where(role: 'user')
   end
   def applicant
   if current_user.role == "admin"
    @applied_jobs = AppliedJob.joins(:job).select("applied_jobs.*, jobs.title")
   else 
   # @applied_jobs = AppliedJob.joins(:job).select("applied_jobs.*, jobs.title").where(user_id: current_user.id)
   @applied_jobs = AppliedJob.joins(:job).where(jobs: { user_id: current_user.id }).select("applied_jobs.*, jobs.title")

   end

   end
private
  def job_params
    params.require(:job).permit(:title, :jobtype, :salary, :location, :description)

  end
   def authorize_admin_or_company
    unless current_user.role == 'admin' || current_user.role == 'company'
        flash[:notice] = "You are not authorized to access this page."
        sign_out current_user
        redirect_to root_path
          
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applied_jobs_helper.rb
module AppliedJobsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/applicants/index.html.erb
 <h1>Listing jobs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Jobtype</th>
    <th>Salary</th>
    <th>Location</th>
    <th>Description</th>
  </tr>
 
  <% @jobs.each do |job| %>
    <tr>
      <td><%= job.title %></td>
      <td><%= job.jobtype %></td>
      <td><%= job.salary %></td>
      <td><%= job.location %></td>
      <td><%= job.description %></td>
    
      <td><%= link_to 'apply', applicant_path(job) %></td>
    </tr>
  <% end %>
</table>



<%= button_to 'logout', destroy_user_session_path,method: :delete %>

app/views/applicants/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>
 
<p>
  <strong>JobType:</strong>
  <%= @job.jobtype %>
</p>
 
<p>
  <strong>Salary:</strong>
  <%= @job.salary %>
</p>
 
<p>
  <strong>Location:</strong>
  <%= @job.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>
 
 <h4>you have successfully applied for this job<h4>

<%= link_to 'Back', applicants_path %>

app/views/applied_jobs/display.html.erb
<h1>you have successfully applied for this job</h1>

<%= link_to 'back',   applied_jobs_path %>

app/views/applied_jobs/index.html.erb
 <h1 style="color: black;"><b>USER PORTAL</b></h1>

 <center><h2>List of Jobs</h2></center>
 <%= search_form_for @q, url: :applied_jobs do |form| %>

  

<div class="form-group ">

  
  <%= form.text_field :title_cont, placeholder: "Search by title..." %>


  <%= form.submit 'Search', class: "btn btn-primary" %>
</div>
<% end %>
  <table class="table table-striped">
  <table class="table align-middle">
  <thead>
    <tr>
      
      <th scope="col">Title</th>
      <th scope="col">JobType</th>
      <th scope="col">Salary</th>
      <th scope="col">Location</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
 
  <% @jobs.each do |job| %>
    <tr>
      <td><%= job.title %></td>
      <td><%= job.jobtype %></td>
      <td><%= job.salary %></td>
      <td><%= job.location %></td>
      <td><%= job.description %></td>
      <td><%= link_to 'Show', applied_job_path(job),class:"btn btn-outline-primary" %></td>
      
    </tr>
  <% end %>
</table>



<%= button_to 'myjobs', myjob_applied_jobs_path,class:"btn btn-success",method: :get %>
<center><%= button_to 'logout', destroy_user_session_path,class:"btn btn-secondary",method: :delete %></center>

app/views/applied_jobs/myjob.html.erb
 <center><h1><b>MY JOBS</b></h1></center>

<table class="table table-striped">
  <table class="table align-middle">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Title</th>
      <th scope="col">JobType</th>
      <th scope="col">Salary</th>
      <th scope="col">Location</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
 
  <% @jobs.each do |record| %>
    <tr>
      <td><%= record.id %></td>
      <td><%= record.title %></td>
      <td><%= record.jobtype %></td>
      <td><%= record.salary %></td>
      <td><%= record.location %></td>
      <td><%= record.description %></td>
      
    </tr>
  <% end %>
</table>

<center><%= link_to 'back',  applied_jobs_path,class: "btn btn-secondary" %></center>

app/views/applied_jobs/new.html.erb
<div class="d-flex align-items-center justify-content-center" style="height: 90vh">
<div class="card" style="width: 20rem;" >
  <div class="card border-dark shadow-sm">
  <div class="card-body">
     <h2 class="card-title">Application Form</h2>

<%= form_for @applied_job,data: { turbo: false} do |f| %>
   <p>
   
    <%= f.hidden_field :user_id, value: current_user.id,size: 20 %>
     
  </p>
  <p>
    
    <%= f.hidden_field :job_id, value: params[:job_id] ,size:20 %>
    
  </p>
 <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, value: current_user.name,size:20 %>
     <% @applied_job.errors.full_messages_for(:name).each do |message| %>
      <span><%= message %></span>
    <% end %>
  </p>
  <p>
    <%= f.label :surname %><br>
    <%= f.text_field :surname, value: current_user.surname,size:20 %>
     <% @applied_job.errors.full_messages_for(:surname).each do |message| %>
      <span><%= message %></span>
    <% end %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email, value: current_user.email,size:20 %>
     <% @applied_job.errors.full_messages_for(:email).each do |message| %>
      <span><%= message %></span>
    <% end %>
  </p>
  <p>
    <%= f.label :contactno %><br>
    <%= f.text_field :contactno,size:20 %>
     <% @applied_job.errors.full_messages_for(:contactno).each do |message| %>
      <span><%= message %></span>
    <% end %>
  </p>
  <p>
    <%= f.label :experience %><br>
    <%= f.text_area :experience,size:20 %>
     <% @applied_job.errors.full_messages_for(:experience).each do |message| %>
      <span><%= message %></span>
    <% end %>
  </p>
  
  <p>
  <%= f.label :resume %><br>
  <%= f.file_field :resume %>
   <% @applied_job.errors.full_messages_for(:resume).each do |message| %>
    <span><%= message %></span>
  <% end %>
</p>

 
  <p>
    <%= f.submit("Submit", class: "btn btn-primary") %>
  </p>
<% end %>
<% if flash[:error].present? %>
  <div class="error_message">
    <%= flash[:error] %>
  </div>
<% end %>
</div>
</div>
</div>
</div>

app/views/applied_jobs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>
 
<p>
  <strong>JobType:</strong>
  <%= @job.jobtype %>
</p>
 
<p>
  <strong>Salary:</strong>
  <%= @job.salary %>
</p>
 
<p>
  <strong>Location:</strong>
  <%= @job.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>
 

 
<%= link_to 'apply',  new_applied_job_path(job_id: @job.id),class: "btn btn-primary" %>
<%= link_to 'back',   applied_jobs_path,class: "btn btn-secondary" %>

app/views/interviews/edit.html.erb
<h1>Edit Interview Status</h1>

<%= form_with model: @interview, url: interview_path(@interview), method: :patch do |form| %>
  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, ['In Progress', 'Selected', 'Rejected'], class: 'form-control' %>
  </div>
  <%= form.submit "Update", class: "btn btn-primary" %>
<% end %>

app/views/interviews/new.html.erb
 <div class="d-flex align-items-center justify-content-center" style="height: 90vh">
<div class="card" style="width: 20rem;" >
 <div class="card border-dark shadow-sm">
<div class="card-body">
<h2 class="card-title">Interview</h2>
<%= form_with model: @interview,data: { turbo: false},  local: true do |f| %>
  <%= f.hidden_field :user_id, value: @user_id %>
  <%= f.hidden_field :job_id, value:  @job_id %>
  
  
  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date,size:20 %>
    <% @interview.errors.full_messages_for(:date).each do |message| %>
      <span><%= message %></span>
    <% end %>
  </p>
  <p>
 
    <%= f.label :address %><br>
    <%= f.text_field :address,size:20 %>
    <% @interview.errors.full_messages_for(:address).each do |message| %>
      <span><%= message %></span>
    <% end %>
  </p>
  
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<% if flash[:error].present? %>
  <div class="error_message">
    <%= flash[:error] %>
  </div>
<% end %>
</div>
</div>
</div>
</div>

app/views/interviews/show.html.erb
<h1>Interview Details</h1>

<p>User_Id: <%= @interview.user_id %></p>
<p>Job_Id: <%= @interview.job_id %></p>
<p>Date: <%= @interview.date %></p>
<p>Address: <%= @interview.address %></p>
<p><b>status: <%= @interview.status %></b></p>
 <%= link_to 'Back', applicant_jobs_path,class: "btn btn-warning"%>
 <%= link_to 'edit status', edit_interview_path(@interview),class: "btn btn-primary"%>

app/views/jobs/_form.html.erb
<div class="card" style="width: 20rem;" >
  <div class="card border-dark shadow-sm">
  <div class="card-body">
    


<%= form_with model: @job,data: { turbo: false}, local: true do |form| %>
 

 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
     <% @job.errors.full_messages_for(:title).each do |message| %>
      <span><%= message %></span>
    <% end %>
  </p>
 
  <p>
    <%= form.label :jobtype %><br>
    <%= form.text_field :jobtype %>
     <% @job.errors.full_messages_for(:jobtype).each do |message| %>
      <span><%= message %></span>
    <% end %>
  </p>

  <p>
    <%= form.label :salary %><br>
    <%= form.text_field :salary %>
     <% @job.errors.full_messages_for(:salary).each do |message| %>
      <span><%= message %></span>
    <% end %>
  </p>
 
  <p>
    <%= form.label :location %><br>
    <%= form.text_field :location %>
     <% @job.errors.full_messages_for(:location).each do |message| %>
      <span><%= message %></span>
    <% end %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% @job.errors.full_messages_for(:description).each do |message| %>
      <span><%= message %></span>
    <% end %>
  </p>
 
  
 
  <p>
    <%= form.submit("Submit", class: "btn btn-primary")  %>
  </p>
 
<% end %>
</div>
</div>
</div>

app/views/jobs/all_user.html.erb
<center><h1>Registered User</h1></center>


<center>
  <table class="table table-striped">
  <table class="table align-middle">
  <thead>
    <tr>
      
      <th scope="col">Name</th>
      <th scope="col">Surname</th>
      <th scope="col">Email</th>
      <th scope="col">Role</th>
    </tr>
  </thead>
 
  <% @all_user.each do |record| %>
    <tr>
      <td><%= record.name %></td>
      <td><%= record.surname %></td>
      <td><%= record.email %></td>
      <td><%= record.role %></td>
      
      
    </tr>
  <% end %>
</table>

<%= link_to 'back', jobs_path ,class:"btn btn-info" %>

app/views/jobs/applicant.html.erb
<center><h1>List of Applicants</h1></center>

<table class="table table-striped">
  <table class="table align-middle">
  <thead>
    <tr>
      
      <th scope="col">User_Id</th>
      <th scope="col">Name</th>
      <th scope="col">Surname</th>
      <th scope="col">Email</th>
      <th scope="col">Job_Id</th>
      <th scope="col">Job_Title</th>
      <th scope="col">Resume</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
 <% @applied_jobs.each do |job| %>
  <tr>
    <td><%= job.user_id %></td>
    <td><%= job.name %></td>
    <td><%= job.surname %></td>
    <td><%= job.email %></td>
    <td><%= job.job_id %></td>
    <td><%= job.title %></td>


    <td>
       <% if job.resume.attached? %>
    <%= link_to 'Download Resume', rails_blob_path(job.resume) %>
  <% end %>
    </td>

    <td><%= link_to 'interview',new_interview_path(user_id: job.user_id,job_id: job.job_id) ,class: "btn btn-info" %></td>
    <% interview = Interview.find_by(user_id: job.user_id, job_id: job.job_id) %>

    <% if interview.present? %>
    <td><%= link_to 'status', interview_path(id: interview.id), class: "btn btn-info" %></td>
    <% end %>

  </tr>
<% end %>
  
</table>


<center><%= link_to 'back', jobs_path ,class: "btn btn-info" %></center>

app/views/jobs/edit.html.erb
<h1>Edit job</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
 <% if current_user.role == "admin" %>
   <h1 style="color: black;"><b>ADMIN PORTAL</b></h1>
<% else %>
  <h1 style="color: black;"><b>COMPANY PORTAL</b></h1>
<% end %>

 

 <center><h2>List of Jobs</h2></center>
<center>
  <div style="overflow-y: scroll; height: 600px;">
  <table class="table table-striped">
  <table class="table align-middle">
  <table class="table table-striped table-fixed">
   <thead style="position: sticky; top: 0; background-color: white;">
    <tr>
      
       <th scope="col">Title</th>
      <th scope="col">JobType</th>
      <th scope="col">Salary</th>
      <th scope="col">Location</th>
      <th scope="col">Description</th> 
        <th scope="col">Action</th> 
    </tr>
  </thead>
  <tbody>
  <% @jobs.each do |job| %>
    <tr>
      <td><%= job.title %></td>
      <td><%= job.jobtype %></td>
      <td><%= job.salary %></td>
      <td><%= job.location %></td>
      <td><%= job.description %></td>
      <td><%= link_to 'Show', job_path(job) ,class:"btn btn-outline-primary" %></td>
      <td><%= link_to 'Edit', edit_job_path(job),class:"btn btn-outline-success" %></td>
       <td><%= link_to 'Destroy', job_path(job),class:"btn btn-outline-danger",
              method: :delete,
              data: { "turbo-method": :delete, confirm: 'Are you sure?'  }
               %></td>
    </tr>
  <% end %>
</tbody>
</table>
</table>
</table>
</div>
</center>
<br>
<%= link_to 'New job', new_job_path,class:"btn btn-success" %>
<%= link_to 'All Users', all_user_jobs_path,class: "btn btn-primary"%>
<%= link_to 'Applicant', applicant_jobs_path,class: "btn btn-warning"%>

 <center><%= button_to 'logout', destroy_user_session_path,class: "btn btn-secondary",method: :delete %></center>

app/views/jobs/new.html.erb
<h1>New job</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>
 
<p>
  <strong>JobType:</strong>
  <%= @job.jobtype %>
</p>
 
<p>
  <strong>Salary:</strong>
  <%= @job.salary %>
</p>
 
<p>
  <strong>Location:</strong>
  <%= @job.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>
 

 
<%= link_to 'Edit', edit_job_path(@job),class: "btn btn-info" %> |
<%= link_to 'Back', jobs_path,class: "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <div class="container"> 
      <%= yield %>
    </div>
  </body>
</html>